<?php
namespace Technolix\KudaopenApiPhp;

class KudabankConstants
{
    protected const  ADMIN_CREATE_VIRTUAL_ACCOUNT =  "ADMIN_CREATE_VIRTUAL_ACCOUNT";
    protected const  ADMIN_RETRIEVE_SINGLE_VIRTUAL_ACCOUNT =  "ADMIN_RETRIEVE_SINGLE_VIRTUAL_ACCOUNT";
    protected const  ADMIN_RETRIEVE_MAIN_ACCOUNT_BALANCE =  "ADMIN_RETRIEVE_MAIN_ACCOUNT_BALANCE";
    protected const  RETRIEVE_SINGLE_VIRTUAL_ACCOUNT =  "RETRIEVE_SINGLE_VIRTUAL_ACCOUNT";
    protected const  BANK_LIST =  "BANK_LIST";
    protected const  NAME_ENQUIRY =  "NAME_ENQUIRY";
    protected const  SINGLE_FUND_TRANSFER =  "SINGLE_FUND_TRANSFER";
    protected const  VIRTUAL_ACCOUNT_FUND_TRANSFER =  "VIRTUAL_ACCOUNT_FUND_TRANSFER";
    protected const  TRANSACTION_STATUS_QUERY =  "TRANSACTION_STATUS_QUERY";
    protected const  RETRIEVE_VIRTUAL_ACCOUNT_BALANCE =  "RETRIEVE_VIRTUAL_ACCOUNT_BALANCE";
    protected const  ADMIN_MAIN_ACCOUNT_TRANSACTIONS =  "ADMIN_MAIN_ACCOUNT_TRANSACTIONS";
    protected const  ADMIN_MAIN_ACCOUNT_FILTERED_TRANSACTIONS =  "ADMIN_MAIN_ACCOUNT_FILTERED_TRANSACTIONS";
    protected const  ADMIN_VIRTUAL_ACCOUNT_TRANSACTIONS =  "ADMIN_VIRTUAL_ACCOUNT_TRANSACTIONS";
    protected const  ADMIN_VIRTUAL_ACCOUNT_FILTERED_TRANSACTIONS =  "ADMIN_VIRTUAL_ACCOUNT_FILTERED_TRANSACTIONS";
    protected const  FUND_VIRTUAL_ACCOUNT =  "FUND_VIRTUAL_ACCOUNT";
    protected const  WITHDRAW_VIRTUAL_ACCOUNT =  "WITHDRAW_VIRTUAL_ACCOUNT";
}
